name: Build and test 🔧💉

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js 24
      uses: actions/setup-node@v6
      with:
        node-version: 24.x
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
    - name: Check formatting
      run: yarn rescript format -check
    - name: Run the tests 👀
      run: yarn test
